#service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro
  namespace: default
---
#role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: micro-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
#RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RoleBinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: micro
  namespace: default
roleRef:
  kind: Role
  name: micro-role
  apiGroup: rbac.authorization.k8s.io
